name: flutter_opl
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  awesome_snackbar_content: ^0.1.4
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  icons_launcher: ^3.0.0
  equatable: ^2.0.5
  dropdown_search: ^6.0.1
  material_design_icons_flutter: ^7.0.7296
  connectivity_plus: ^6.1.0
  in_app_update: ^4.2.3
  permission_handler: ^11.3.1
  dartz:
  logger:
  get_it:
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
